### PR TITLE
refactor render pipeline

### PR DESCRIPTION
**Pull request by stohrendorf**
CE-386

Unfortunately, this became a little bit larger than originally planned.
* crt filter is now be properly applied as a final full screen effect
* fxaa shader replaced with one that actually works
* fxaa quality preset selection from display settings
* increased bloom visibility

### CODE REVIEW

**Review by serishema — APPROVED** [review]
I tested this under the different rendering settings and in water / not in water and it all works correctly.
I haven't written GLSL in a long time, but the new FXAA shader has very good performance even on a GTX 650 in colosseum on high it doesn't drop the framerate at all. 
Good Work.

**Comment by stohrendorf** [comment]
Unfortunately it seems I need to tweak some FXAA settings, as it adds a massive amount of blur, which in addition to other blurring effects (like depth of field or bloom) results in a totally blurred and ugly image.

**Comment by serishema** [comment]
I had another look. In colleseum with depth of feild and fxaa on I notice lara looks out of focus, which doesn't happen in caves. It seems to depend on the lighting.  
In future i'll try graphics options together and in isolation.

**Comment by stohrendorf** [comment]
Did some invasive changes to this pull request. FXAA finally seems to work now, blurring doesn't seem to occur anymore that much except for the wanted blur.

**Pull request merged**
