### PR TITLE
add animation smoothing

### PR DESCRIPTION
**Pull request by stohrendorf**
Slightly smoothes animations to have less impact from badly built, quivering animations.

### CODE REVIEW

**Review by serishema — CHANGES_REQUESTED** [review]
The smoothing itself looks OK.

But I discovered that if you start the game, then go into the menu and toggle the ghost on, when trying to exit back to the main menu it crashes on `skeletalmodelnode.cpp` line 322 after answering whether to save the recorded ghost. 
This only occurs when initally turning the ghost on while in the game. It seems that if ghost is on in the config file when CE starts, it won't crash but changing it during runtime is problematic. 
I'm not sure of the cause.

here's a stack trace
```
	croftengine.exe!engine::SkeletalModelNode::rebuildMesh::__l15::<lambda>() Line 322	C++
 	croftengine.exe!engine::SkeletalModelNode::getMeshMatricesBuffer(std::function<bool __cdecl(void)> smooth) Line 368	C++
 	croftengine.exe!render::scene::BufferParameter::bindBoneTransformBuffer::__l2::<lambda>(const render::scene::Node * node, const render::scene::Mesh & __formal, gl::ProgramBlock<37606,37074> & ssb) Line 46	C++
 	croftengine.exe!render::scene::BufferParameter::bind(const render::scene::Node * node, const render::scene::Mesh & mesh, const gsl::not_null<std::shared_ptr<render::scene::ShaderProgram>> & shaderProgram) Line 38	C++
 	croftengine.exe!render::scene::Material::bind(const render::scene::Node * node, const render::scene::Mesh & mesh) Line 57	C++
 	croftengine.exe!render::scene::Mesh::render(const render::scene::Node * node, render::scene::RenderContext & context) Line 75	C++
 	croftengine.exe!menu::MenuObject::draw(const engine::world::World & world, const menu::MenuRingTransform & ringTransform, const qs::quantity<core::_Angle_generated_unit,int> & ringItemAngle) Line 188	C++
 	croftengine.exe!menu::MenuDisplay::display(ui::Ui & ui, engine::world::World & world) Line 162	C++
 	croftengine.exe!engine::Engine::runTitleMenu(engine::world::World & world) Line 591	C++
 	croftengine.exe!engine::script::TitleMenu::run(engine::Engine & engine, const std::shared_ptr<engine::Player> & player, const std::shared_ptr<engine::Player> & levelStartPlayer) Line 251	C++
 	croftengine.exe!engine::Engine::runLevelSequenceItem(engine::script::LevelSequenceItem & item, const std::shared_ptr<engine::Player> & player, const std::shared_ptr<engine::Player> & levelStartPlayer) Line 642	C++
 	croftengine.exe!main(int argc, char * * argv) Line 205	C++
 	croftengine.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
```

**Comment by stohrendorf** [comment]
Thank you. I was concerned about ghosts, but didn't consider them such a major issue. i will look into it.

**Comment by stohrendorf** [comment]
Turns out the issue was the material cache, which cached the function, which would then use whatever function was passed in when initially creating the material.

**Review by serishema — APPROVED** [review]
Tested the ghost enable/disable again and with the fix it's stable now. 
Lara's movements seem a bit more natural.
Good work.

**Pull request merged**
