### PR TITLE
switch to 60 fps

### PR DESCRIPTION
**Pull request by stohrendorf**

### CODE REVIEW

**Comment by Sol1vaN** [comment]
Sorry for my ignorance, but its possible that you make even more 60FPS feature?
Like the XProger code (OpenLara) that's already have FPS unlocked (even for 120FPS, or more)

Source: https://codeload.github.com/XProger/OpenLara/zip/refs/tags/latest

Right now I've 120hz monitor, and OpenLara looks sweet with vzync 120fps@120hz

**Comment by stohrendorf** [comment]
Unfortunately I encountered a lot of problems with the 60 fps experiment, because it breaks the original gameplay in a lot of ways which I wasn't able to solve yet. Building it for 60 fps only already helped me avoid a lot of other problems. I stopped working on this a while ago because of these problems.

**Comment by Sol1vaN** [comment]
> Unfortunately I encountered a lot of problems with the 60 fps experiment, because it breaks the original gameplay in a lot of ways which I wasn't able to solve yet. Building it for 60 fps only already helped me avoid a lot of other problems. I stopped working on this a while ago because of these problems.

Ooh that's is very infortunate to see this 😥
I see the same problems with the 60FPS case on others engines.
This guy (Kaze Emanuar) explain the way he approach this to solve this challenge on Mario 64 engine.

Can you take a look:
https://www.youtube.com/watch?v=t_rzYnXEQlE

Or: take the another source engine like XProger code, but ey! I know all this take a lot of time and effort, your work until now is impressive, thanks for this!

Even with the 30FPS locked the game looks charming, again, thanks for this 😎👍

**Comment by stohrendorf** [comment]
OpenLara has a completely different architecture than this engine, so it won't help me figuring this out.

**Comment by stohrendorf** [comment]
Closing this because it's outdated beyond any hope of recovery.

**Pull request closed without merging**
