### PR TITLE
don't do anything if the keyhole already had its key inserted

### PR DESCRIPTION
**Pull request by stohrendorf**
fixes CE-540

### CODE REVIEW

**Review by serishema — APPROVED** [review]
I didn't test this, but looks like this will work.
State gets seralized into the save so I don't think the issues with having to change the save format you were concerned about will occur.

**Comment by stohrendorf** [comment]
Thanks for mentioning the saves, didn't really think about that. But as the trigger state is already saved to the saves, this will (hopefully) only prevent multiple insertions of the keys, also for already saved games, as successfully inserting the key will set the trigger state to "active", which is now checked as a prerequisite. Blame me if it breaks things.

**Comment by serishema** [comment]
yup, I agree with that assessment. If you have an example of a level where you could insert keys twice, I can test it.

**Comment by stohrendorf** [comment]
Best option I can currently think of is to add some cheats in the gameflow scripts and then run to the first door in city of vilcabamba.

**Comment by serishema** [comment]
I gave it a try on the first door in vilcabamca. It didn't work. 
Seems to require a 
`if(m_state.triggerState == TriggerState::Deactivated)
   return;`
as well to get the desired effect, but I don't know if this is correct.

**Comment by stohrendorf** [comment]
That's correct, totally forgot there's a special `triggerKey` handler that deactivates the keyhole.

**Pull request merged**
